### ISSUE TITLE
Using Dapper with HotChocolate Paging/Filtering

### ISSUE THREAD

**Issue by scottetass** [Tim-Maes/GraphR#11]
Great template so far, thanks !

I have encountered problems with using Dapper in HotChocolate, let me explain using your books example.

Say your books table has 20,000 records in it. You don't want to return all 20,000 records in the one call as that could be inefficient so you utilize paging in HC to return a page size of 100 records. But paging is the last thing that HC applies to the return records in it's middleware, so that means your repository would have to return all records in the table to the API, and materialize those records in memory, so that HC can apply paging and ultimately throw away 19,900 records each time the caller asks for a new page. This is extremely inefficient and could cause memory issues on very large tables.

I haven't yet found an easy way to get access to the HC query parameters so that you could pass down the paging details to the query in the repository to apply paging at the query level and avoid returning unwanted data to the API.

I guess you could implement your own paging input parameters somehow but that is just duplicating what HC has already developed.

Have you come across this issue and had any thoughts on how to handle it and perhaps build that into the template?

**Comment by Tim-Maes** [comment]
Hi Scottetass!

Thank you for your feedback !

In my previous solutions, I was not using HotChocolate but the GraphQl.NET library, and the skip&take principle was applied by passing the parameters directly from the request to the Dapper query using `OFFSET` and `FETCH NEXT`. It is a simple, and working solution to the problem at that time. HotChocolate is 'hot' right now, evolving fast and had the Subscription type support, which I was missing so I decided to use it for this template.

I have not looked into this issue using HotChocolate yet I'm afraid. A quick glance at the [documentation](https://chillicream.com/docs/hotchocolate/v12/fetching-data/pagination) tells me that the pagination is implemented with the purpose of reducing the amount of data sent to the frontend in the API layer, not reducing the amount of data queried on the database level. At the moment I think some sort of custom implementation (or extension) would be required to achieve this unless I'm missing something, would need to investigate some more. 

Subscriptions and DataLoaders are still on my TODO list to add to the template examples, if we find a good approach for pagination I will add it too.
